## Shared Micromobility Vehicle Trips Data

### Data Source and API
- AODP Dataset Access: https://data.austintexas.gov/Transportation-and-Mobility/Shared-Micromobility-Vehicle-Trips/7d8e-dm7r
- API Endpoint: https://data.austintexas.gov/resource/7d8e-dm7r.json
- API Documentation: https://dev.socrata.com/foundry/data.austintexas.gov/7d8e-dm7r

To access the dataset host, install SODA API first:

`pip install sodapy`

### Data Extraction
- Data Provided
    - trip_id
    - device_id
    - modified_date
    - council_district_start
    - council_district_end
    - vehicle_type
    - trip_duration
    - trip_distance
    - start_time
    - end_time
    - month
    - hour
    - day_of_week
    - year
    - census_geoid_start
    - census_geoid_end

In [10]:
# Dependencies and packages
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import math as math
import datetime as dt
import seaborn as sns

In [10]:
# Output File (CSV)
output_data_file = "Output_Data/shared_mobility.csv"

In [21]:
# url = https://data.austintexas.gov/resource/7d8e-dm7r.json

import pandas as pd
from sodapy import Socrata

client = Socrata("data.austintexas.gov", None)

results = client.get("7d8e-dm7r", limit=8000000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [22]:
results_df.head()

,trip_id,device_id,modified_date,council_district_start,council_district_end,vehicle_type,trip_duration,trip_distance,start_time,end_time,month,hour,day_of_week,year,census_geoid_start,census_geoid_end
0,6865731e-5e4b-4819-9435-4e62e09a652d,08c8c852-257c-49ad-a14f-727bfc79626d,2018-12-13T15:36:12.000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,08dc0d9c-735e-4006-b9af-60011509e469,255716b5-4a9f-4efc-9967-7a65b3521bac,2018-12-21T00:41:42.000,9,0,bicycle,11491603,1658,2018-11-30T11:00:00.000,2019-04-12T12:00:00.000,11,11,5,2018,NaN,NaN
2,92b80c20-89a4-4c7f-8b61-81a3570a218e,4d1e7bd0-75ce-401c-a802-8dd87122f802,2019-04-28T02:42:07.000,1,9,scooter,678,2785,2019-04-27T15:00:00.000,2019-04-27T15:15:00.000,4,15,6,2019,48453001100,48453001100
3,d9aef7c5-025d-4f2c-bafe-7801f89ef9dd,fdc38815-fe35-454b-bfb9-a63a2f2c205b,2019-04-28T02:42:07.000,9,5,scooter,713,2466,2019-04-27T15:00:00.000,2019-04-27T15:15:00.000,4,15,6,2019,48453001305,48453001901
4,baec3b6e-66f1-4043-bbd5-d54087f1c2de,007f1fed-0fe6-423f-8ca7-cd67834f20da,2019-04-28T02:42:07.000,9,9,scooter,469,1608,2019-04-27T15:15:00.000,2019-04-27T15:15:00.000,4,15,6,2019,48453001100,48453001305

In [24]:
# Check for missing values 
results_df.count()

trip_id                   800000
device_id                 800000
modified_date             800000
council_district_start    799996
council_district_end      799996
vehicle_type              799999
trip_duration             799999
trip_distance             799999
start_time                799999
end_time                  799999
month                     799999
hour                      799999
day_of_week               799999
year                      799999
census_geoid_start        799994
census_geoid_end          799994
dtype: int64